### ISSUE TITLE
it looks terrific, but....

### ISSUE THREAD

**Issue by todocono** [wiotio/wESP#1]
I am really interested in your work. It looks awesome! congratulations!

I was not able to compile it in any environment. I tried Arduino 1.65 with the original ESP board library, 1.6.8 with ESP 2.0.0 (my personal favorite) and 1.6.9 with 2.2.0. 

Any clues what is different in my structure? I am working with nodeMCU 1 and 0.9

These are the errors the compiler spits: 

`Arduino: 1.6.9 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

In file included from /workspace/Arduino/wESP/wESP.ino:14:0:
sketch/helpers.h: In function 'boolean summertime(int, byte, byte, byte, byte)':
sketch/helpers.h:30:15: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
  if (month==3 && (hour + 24 * day)>=(1 + tzHours + 24*(31 - (5 * year /4 + 4) % 7)) || month==10 && (hour + 24 * day)<(1 + tzHours + 24*(31 - (5 * year /4 + 1) % 7)))
               ^
In file included from /workspace/Arduino/wESP/wESP.ino:14:0:
sketch/helpers.h: In function 'void WriteStringToEEPROM(int, String)':
sketch/helpers.h:56:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (int t=  0; t<sizeof(charBuf);t++)
                                  ^
/workspace/Arduino/wESP/wESP.ino: At global scope:
wESP:35: error: 'callback' was not declared in this scope
 PubSubClient client(config.MqttBroker.c_str(), 1883, callback, wifiClient);
                                                      ^
/workspace/Arduino/wESP/wESP.ino: In function 'void setup()':
wESP:84: error: 'macToStr' was not declared in this scope
       APssid += macToStr(mac);
                             ^
wESP:111: error: 'send_togglea_config' was not declared in this scope
   server.on ( "/admin/togglea", send_togglea_config);
                                 ^
wESP:112: error: 'send_toggleb_config' was not declared in this scope
   server.on ( "/admin/toggleb", send_toggleb_config);
                                 ^
/workspace/Arduino/wESP/wESP.ino: In function 'void loop()':
wESP:137: error: 'reconnect' was not declared in this scope
   if (!client.connected() && WiFi.status() == 3) {reconnect();}
                                                             ^
/workspace/Arduino/wESP/wESP.ino: In function 'void reconnect()':
wESP:215: error: 'macToStr' was not declared in this scope
       clientName += macToStr(mac);
                                 ^
exit status 1
'callback' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by wiotio** [comment]
Hi todocono,
Sorry for late reply my business is too much at these days. I think your problem is with the pubsub client which must be PubSubClient 2.6.0 by Nick O'Leary. And check you have Ticker.h & EEPROM.h library.

My setup is Arduino 1.6.5 and other libraries is in wESP.ino;
ESP8266WiFi.h
WiFiClient.h
PubSubClient.h
ESP8266WebServer.h
Ticker.h
EEPROM.h
WiFiUdp.h

**Comment by todocono** [comment]
Thank you for that... I will try it if I can these days. Meanwhile I am
using the WifiManager quite happily.

2016-07-14 19:31 GMT+08:00 wiotio <notifications@github.com>:

**Comment by Ukhauk** [comment]
looks like a great interface, I get the following error compiling on ardino 1.6.9

Documents\Arduino\wESP-master\wESP\wESP.ino: In function 'void reconnect()':
wESP:215: error: 'macToStr' was not declared in this scope
exit status 1
'callback' was not declared in this scope

**Comment by wiotio** [comment]
if everyone gets error it is best ending the project.
